const { validationResult } = require("express-validator")
const sendResponse = require("../utils/response")

// reusable validation middleware
// runs after express-validator rules have been executed
const validate = (req, res, next) => {
    // collect all validation errors generated by the validators
    const errors = validationResult(req)

    // if any validation errors exist, stop the request and send a 400 Bad Request reponse
    if(!errors.isEmpty()) {
        return sendResponse(res, 400, false, "Validation failed", errors.array())
    }
    // no validation errors
    // continue to the next middleware/controllers
    next()
}

module.exports = {validate}
